// Define the component types that will be available for styling
export const componentTypes = [
    // Root and layout
    'root',
    'layout',
    'container',
    'section',
    'grid',
    'flexbox',

    // Form elements
    'text',
    'number',
    'textarea',
    'selectsingle',
    'selectmany',
    'checkbox',
    'radio',
    'switch',
    'button',
    'date',
    'color',
    'file',
    'email',
    'password',
    'url',
    'tel',
    'search',

    // Special elements
    'shadow',
    'label',
    'paragraph',
    'notice',
    'markdown',
    'question',
    'preview',
    'richtext',
    'map',
    'legal-consent',
    'rating',
    'ranking',
    'slider',
    'slider-range',
    'number-range',
    'social-textarea',
    'data-view',
    'generated',
    'date-time-picker',
    'code',
    'cron',
    'icon-picker',
    'uuid',
    'phone',
    'data-lookup-combo',
    'avatar',
    'badge',
    'tooltip',
    'popover',
    'modal',
    'drawer',
    'alert',
    'toast',
    'progress',
    'spinner',
    'stepper',
    'timeline',
    'tag',
    'chip',

    // Layout components
    'accordion',
    'tab',
    'slider-layout',
    'collapsible',
    'form',
    'card',
    'panel',
    'divider',
    'list',
    'menu',
    'navbar',
    'sidebar',
    'footer',
    'header',
    'breadcrumb',
    'pagination'
];

// Define the component parts for each component type
export const componentParts = {
    // Additional layout components
    container: ['wrapper', 'inner', 'content', 'header', 'body', 'footer'],
    section: ['container', 'header', 'title', 'subtitle', 'content', 'footer'],
    grid: ['container', 'row', 'column', 'item', 'gutter'],
    flexbox: ['container', 'item', 'grow', 'shrink', 'basis'],
    // Common layout components
    root: ['container', 'header', 'body', 'footer', 'submitButton', 'cancelButton'],
    layout: ['container', 'tabsContainer', 'tab', 'activeTab', 'inactiveTab', 'content', 'item', 'header', 'icon'],

    // Form elements - Input elements
    text: ['container', 'label', 'label-inner', 'input-container', 'input', 'prefix', 'suffix', 'description', 'error', 'helpContainer', 'icon', 'iconContainer', 'placeholder', 'focusIndicator', 'disabledState', 'readOnlyState', 'validState', 'invalidState'],
    number: ['container', 'label', 'input', 'prefix', 'suffix', 'stepper', 'stepperUp', 'stepperDown', 'description', 'error'],
    textarea: ['container', 'label', 'input', 'resize-handle', 'description', 'error'],
    selectsingle: ['container', 'label', 'dropdown', 'option', 'description', 'error'],
    selectmany: ['container', 'label', 'dropdown', 'option', 'description', 'error'],
    checkbox: ['container', 'option', 'input', 'label', 'description', 'error'],
    radio: ['group', 'option', 'optionSelected', 'optionUnselected', 'label', 'labelSelected', 'labelUnselected', 'icon', 'checkmark', 'description', 'error'],
    switch: ['container', 'track', 'thumb', 'icon', 'label', 'labelOn', 'labelOff', 'description', 'error'],
    button: ['container', 'button', 'label', 'description', 'error'],
    date: ['container', 'input', 'prefix', 'suffix', 'calendar', 'calendarHeader', 'calendarDays', 'calendarDay', 'calendarDaySelected', 'calendarDayToday', 'description', 'error'],
    color: ['container', 'preview', 'palette', 'paletteItem', 'input', 'description', 'error'],
    file: ['container', 'dropzone', 'dropzoneActive', 'button', 'fileList', 'fileItem', 'filePreview', 'fileInfo', 'fileName', 'fileSize', 'progressBar', 'deleteButton', 'errorMessage', 'description', 'error'],

    // Additional form elements
    email: ['container', 'label', 'input', 'prefix', 'suffix', 'description', 'error', 'icon', 'placeholder'],
    password: ['container', 'label', 'input', 'prefix', 'suffix', 'description', 'error', 'icon', 'toggleVisibility', 'placeholder', 'strengthIndicator'],
    url: ['container', 'label', 'input', 'prefix', 'suffix', 'description', 'error', 'icon', 'placeholder'],
    tel: ['container', 'label', 'input', 'prefix', 'suffix', 'description', 'error', 'icon', 'placeholder'],
    search: ['container', 'label', 'input', 'prefix', 'suffix', 'description', 'error', 'icon', 'clearButton', 'placeholder', 'results'],

    // Special elements
    shadow: ['container', 'header', 'button', 'content', 'canvas', 'controls', 'code'],
    label: ['container', 'text'],
    paragraph: ['container'],
    notice: ['container', 'icon', 'title', 'content'],
    markdown: ['container', 'editor'],
    question: ['container', 'label', 'range', 'input'],
    preview: ['container', 'image', 'placeholder'],
    richtext: ['container', 'toolbar', 'toolbarButton', 'editor'],
    map: ['container', 'map', 'controls', 'marker', 'infoWindow'],
    'legal-consent': ['container', 'form', 'label', 'input', 'error', 'buttonContainer', 'acceptButton', 'rejectButton', 'result', 'modifyButton'],
    rating: ['container', 'star', 'starFilled', 'starEmpty', 'starHalf'],
    ranking: ['container', 'grid', 'header', 'headerLabel', 'row', 'optionLabel', 'cell', 'input', 'select', 'option'],
    slider: ['container', 'track', 'thumb', 'rail', 'mark', 'markLabel', 'value', 'input'],
    'slider-range': ['container', 'minTrack', 'maxTrack', 'rail', 'thumb', 'value'],
    'number-range': ['container', 'minInputContainer', 'maxInputContainer', 'minInput', 'maxInput', 'separator'],
    'social-textarea': ['container', 'textarea', 'controls', 'platformSelector', 'iconPicker', 'counter', 'counterWarning', 'counterError', 'suggestions', 'suggestionItem', 'suggestionSelected'],
    'data-view': ['container', 'emptyMessage', 'itemContainer', 'item', 'value', 'key', 'objectContainer', 'objectItem', 'deleteButton'],
    generated: ['container', 'value', 'button', 'icon'],
    'date-time-picker': ['container', 'controls', 'label', 'select', 'checkbox', 'inputContainer', 'input', 'presetSelector', 'error', 'preview', 'previewTitle', 'previewContent'],
    code: ['container', 'editor', 'appBar', 'button', 'saveButton', 'expandButton', 'loading'],
    cron: ['container', 'expressionContainer', 'expression', 'summary', 'button', 'primaryButton', 'secondaryButton', 'tabsContainer', 'tab', 'activeTab', 'tabContent', 'fieldContainer', 'label', 'input', 'select', 'dayButton', 'activeDayButton', 'quickButton'],
    'icon-picker': ['container', 'icon', 'button', 'dropdown', 'search', 'option', 'selectedOption'],
    uuid: ['container', 'value', 'button', 'icon'],
    phone: ['container', 'dropdownButton', 'dropdownMenu', 'dropdownItem', 'dropdownItemSelected', 'input', 'flag'],
    'data-lookup-combo': ['container', 'error', 'selectedItems', 'controls', 'input', 'searchButton', 'results', 'resultsHeader', 'resultsCount', 'resultsList', 'resultsItem', 'item', 'removeButton', 'itemTitle', 'itemDate'],

    // Additional special elements
    avatar: ['container', 'image', 'placeholder', 'badge', 'text', 'icon'],
    badge: ['container', 'content', 'dot', 'text', 'icon'],
    tooltip: ['container', 'content', 'arrow', 'title', 'description'],
    popover: ['container', 'content', 'arrow', 'header', 'body', 'footer', 'closeButton'],
    modal: ['container', 'overlay', 'content', 'header', 'body', 'footer', 'closeButton', 'title'],
    drawer: ['container', 'overlay', 'content', 'header', 'body', 'footer', 'closeButton', 'title'],
    alert: ['container', 'icon', 'title', 'content', 'closeButton', 'actions'],
    toast: ['container', 'icon', 'content', 'closeButton', 'progress'],
    progress: ['container', 'track', 'indicator', 'label', 'value'],
    spinner: ['container', 'track', 'indicator', 'label'],
    stepper: ['container', 'step', 'stepActive', 'stepCompleted', 'stepError', 'connector', 'label', 'description', 'icon'],
    timeline: ['container', 'item', 'itemActive', 'connector', 'dot', 'content', 'time', 'title', 'description'],
    tag: ['container', 'label', 'icon', 'closeButton'],
    chip: ['container', 'avatar', 'label', 'icon', 'deleteIcon'],

    // Layout components
    accordion: ['container', 'item', 'header', 'content', 'icon'],
    tab: ['container', 'tabsContainer', 'tab', 'activeTab', 'inactiveTab', 'content'],
    'slider-layout': ['container', 'slide', 'controls', 'prevButton', 'nextButton', 'indicator', 'activeIndicator'],
    collapsible: ['container', 'header', 'icon', 'title', 'content'],
    form: ['container', 'header', 'body', 'footer', 'submitButton', 'cancelButton'],

    // Additional layout components
    card: ['container', 'header', 'media', 'content', 'title', 'subtitle', 'description', 'actions', 'footer'],
    panel: ['container', 'header', 'title', 'content', 'footer', 'actions'],
    divider: ['container', 'line', 'text', 'icon'],
    list: ['container', 'item', 'itemActive', 'itemSelected', 'icon', 'text', 'secondaryText', 'action'],
    menu: ['container', 'item', 'itemActive', 'itemSelected', 'icon', 'text', 'submenu', 'divider'],
    navbar: ['container', 'brand', 'links', 'link', 'linkActive', 'actions', 'toggle', 'collapse'],
    sidebar: ['container', 'header', 'content', 'footer', 'item', 'itemActive', 'itemCollapsed', 'toggle'],
    footer: ['container', 'section', 'links', 'copyright', 'social', 'logo'],
    header: ['container', 'logo', 'navigation', 'actions', 'search'],
    breadcrumb: ['container', 'item', 'itemActive', 'separator', 'icon', 'text'],
    pagination: ['container', 'item', 'itemActive', 'itemDisabled', 'previous', 'next', 'ellipsis']
};
